### PR TITLE
Updating readme

### PR DESCRIPTION
**Pull request by MichaelPesce**

### CODE REVIEW

**Comment by dangunter** [comment]
I don't understand why updating README has 17 files changed?

**Comment by elbashandy** [comment]
@MichaelPesce The changes make sense. But you haven't updated your local git repo in your machine to match the origin upstream. As a result, a lot of other files that we already moved around are being committed with your changes. I will update your branch for now, and we can do future PRs together later on.

A good source to update a branch:
https://www.atlassian.com/git/tutorials/syncing/git-fetch
https://www.atlassian.com/git/tutorials/merging-vs-rebasing

Feel free to ask me any questions about this.

**Comment by elbashandy** [comment]
Oh I just checked your changes more thoroughly. You actually used the most updated branch. Sorry about that. The changes make sense. We are renaming a folder which in turn changed a lot of files. I did that in another PR. Great job Mike. It's great that you added them in two separate commits. For future reference, mention these details in the description/title so the reviewer can understand what to look for in your code.

**Review by elbashandy — APPROVED** [review]
Looks good to me! @dangunter let's merge this.

**Comment by MichaelPesce** [comment]
Yeah sorry I didn't make that clear. I didn't actually change the contents of most of those files, just renamed the components folder as AR pointed out, because the imports were all throwing errors. I'll make sure to be more elaborate in the future.

**Pull request merged**
