### PR TITLE
Use Conda environment file to manage frontend and backend dependencies

### PR DESCRIPTION
**Pull request by lbianchi-lbl**
## TODO

- [ ] Verify that the commands work on Windows

### CODE REVIEW

**Comment by lbianchi-lbl** [comment]
Note to self/for posterity: the Cypress error on Linux looks similar to this issue: https://github.com/cypress-io/cypress/issues/21532.

**Comment by lbianchi-lbl** [comment]
@MichaelPesce While discussing this PR during the dev call I thought of a potential cause for the test failing on Windows, namely something connected with static assets (i.e. images, icons, standalone JS files, etc) not being found. This is just a guess at this point, but it could in principle be a cause according to the following criteria:

- Why is it showing up only in this PR? This PR changes the way packages are installed (both Python and JS), which does affect where files are installed on the filesystem especially for the Python code
- Why only on Windows? This is less clear, but it could be due to OS-specific differences such as path separators, symlinks, case-sensitiveness, etc

I'll look into this in more depth to try to address the failures.

**Comment by lbianchi-lbl** [comment]
The changes that @MichaelPesce implemented for #35 seem to be working and the Windows checks are now passing! I'm switching this back to draft mode as I plan to add a few minor changes. We should plan on merging #35 first and then this PR.

**Comment by lbianchi-lbl** [comment]
@dangunter feel free to take a look (the most relevant changes are in README.md and the environment file I think) and let us know what you think. @MichaelPesce and I are ready to merge this whenever.

**Review by MichaelPesce — APPROVED** [review]

**Pull request merged**
