### PR TITLE
Startup behavior & modified download

### PR DESCRIPTION
**Pull request by dangunter**
This PR creeped a bit in scope, but the main change is to avoid building every flowsheet at startup, and doing some refactoring of how the list of flowsheets is represented (in anticipation of needing to refactor more when we have different "views" if the same flowsheet in the future).

### CODE REVIEW

**Comment by MichaelPesce** [comment]
The changes look good to me. The tests failed because of the removal of the package-lock.json, which is needed for npm clean installs. We can either modify the workflow to perform a regular install, or add the package-lock.json back into the repo to fix that; not sure which way is better practice

**Review by MichaelPesce — APPROVED** [review]

**Comment by dangunter** [comment]
@MichaelPesce I put back package-lock now that I understand what it is. I also "fixed" the test to deal with the 2 columns I removed from the flowsheet-list display.

**Comment by MichaelPesce** [comment]
@dangunter looks like one of the component tests needs to be updated as well (FlowsheetsListTable.test.js). It seems like it has something to do with how the flowsheet name is being displayed for the list. Not sure exactly what needs to be changed but if we merge this I can pull the changes and update the test

**Comment by MichaelPesce** [comment]
@dangunter  I think the tests failed in the CI workflow because the backend had an error starting up. It might have to do with the removal of `self._save_default_flowsheet()` in line 21 of flowsheet.py. Not sure if that code can be put back in the same spot though, because the flowsheet build takes place somewhere else now

**Comment by dangunter** [comment]
Superseded by API rewrite

**Pull request closed without merging**
