### PR TITLE
Implemented frontend changes to work with updated API

### PR DESCRIPTION
**Pull request by MichaelPesce**
issue #38

### CODE REVIEW

**Comment by dangunter** [comment]
@MichaelPesce for running the UI I get an error:
```
❯ npm run electron-start

> nawi-ui@0.1.0 electron-start
> concurrently -k "cross-env npm run app-start-nob" "wait-on http://localhost:3000 && npx electron ."

'concurrently' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by MichaelPesce** [comment]
@dangunter hmm did you try `npm install` inside the electron directory? could also try installing it on its own: `npm i concurrently`

**Comment by dangunter** [comment]
that line is not going to ever work on windows

**Comment by dangunter** [comment]
I found another bug, with the categories display. Basically we should not display "empty" categories in either the input or output screens. I'm not sure what the "Uncategorized" thing is in the input screen, but in the output screen it seems to get confused by the categories that have only input variables in them.

Input

image

Output

image

**Comment by dangunter** [comment]
Note: for testing install watertap from Tim's "metab_ui" PR, which should now work well enough to reproduce this behavior. 

https://github.com/watertap-org/watertap/pull/698

**Comment by dangunter** [comment]
I thought of a minor thing (could be a separate PR) for the display of the inputs [and maybe outputs]. To eliminate the space between categories with less things side-by-side with categories with more things, you could stack the categories in each column. This will require deciding ahead of time something about the limit on column-height or how to distribute the boxes. Maybe there is a layout algorithm that can basically do it for you if you set the height equal to something based on (boxes + inputs) / 2.

**Review by dangunter — APPROVED** [review]
It works nicely now.

**Pull request merged**
